### ISSUE TITLE
Support for VS 2017

### ISSUE THREAD

**Issue by kinju4374** [christianhelle/reswcodegen#1]
Please add support for Visual Studio 2017.

**Comment by christianhelle** [comment]
I partially support it now, and the installer works but I can't seem to get rid of a compatibility warning. A lot has changed in the Visual Studio 2017 SDK and I'm having a surprisingly hard time to get backwards compatibility to work

**Comment by kinju4374** [comment]
Ok. Are you going to release it just for VS 2017 as you mentioned in your CodePlex comments post?

**Comment by christianhelle** [comment]
Yes, I will probably go in that direction, I mean creating a VS 2017 only release. 

This way I can go away from this lazy hack that I have been doing all this time. The current code actually still references VS 2012 SDK libraries and for some reason works without any problems on VS 2013 and VS 2015, but in VS 2017 I get install time warnings

**Comment by kinju4374** [comment]
Ok. Same thing happened with me for my Windows Phone 8 project, they stopped support of WP8/8.1 projects in VS2017.

**Comment by christianhelle** [comment]
I haven't really been using Visual Studio 2017 that much since it came out. I will eventually fully move to it once ReSharper officially supports a stable release for it

**Comment by kinju4374** [comment]
Any update on this? I was checking and found that @madenwala added support for VS 2017

**Comment by bondarenkod** [comment]
Check my fork for working (I hope) build, also read the readme before.
