### ISSUE TITLE
Updating a generated date in the generated file causes annoying merge conflicts

### ISSUE THREAD

**Issue by joellyons** [christianhelle/reswcodegen#128]
The generated .cs files contain a comment at the top that includes the date and time the file was generated. This makes it difficult for merge tools to automatically merge two generated cs files that were both changed recently. Is there an important reason to include the generated date and time in the cs file? If not, it would be nice to remove it to avoid merge conflicts.

I'd be happy to make this change and submit a pull request if you think this is a good idea. Thanks!

**Comment by christianhelle** [comment]
@joellyons thanks for taking the time to report this

The answer is no, now that you mention it, there is absolutely no reason to add a timestamp to the generated code. This can easily go away. 

I would greatly appreciate a pull request and will make sure to get it released to the marketplace as soon as we merge it in

**Comment by christianhelle** [comment]
@joellyons Have you started on a fix? If not, then I can also do it

**Comment by joellyons** [comment]
Oops! I got distracted. It's on my to-do list but I haven't started anything. Feel free to bang it out if you have a moment. Thanks! 😊On Nov 20, 2023 12:48 PM, Christian Helle ***@***.***> wrote:
@joellyons Have you started on a fix? If not, then I can also do it

**Comment by christianhelle** [comment]
I implemented the fix and I expect to release a new version later today

**Comment by joellyons** [comment]
> @joellyons I implemented the fix and I expect to release a new version later today

Excellent! Thank you so much.

**Comment by christianhelle** [comment]
@joellyons  The change were released to the marketplace yesterday as v1.7.15

![image](https://github.com/christianhelle/reswcodegen/assets/710400/52b72756-23e3-44a1-bb38-6ebb0dc82e4b)
